In [44]:
smash = ['Mario', 'DK', 'Link', 'Samus', 'Yoshi',
'Kirby', 'Fox', 'Pikachu']
smash

['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']

In [45]:
smash.extend(['Luigi', 'Ness', 'C. Falcon', 'Jigglypuff'])
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff']

In [46]:
smash.append(['Metal Mario', 'Polygon Team', 'Master Hand'])
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [48]:
temp = ['Original roster']
temp.extend(smash[8:])
smash = temp
smash

['Original roster']

In [11]:
def null_matrix(m,n):
    return [[0]*n]*m
temp = null_matrix(3,4)
temp

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [49]:
[[['?']*2]*3]*4

[[['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']]]

In [50]:
mensualidad = {'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}
mensualidad

{'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}

In [51]:
mensualidad.pop('Disney+')
mensualidad['Blim'] = 109
mensualidad['Netflix'] = 139
mensualidad['Prime'] = 99
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109}

In [52]:
import numpy as np

In [53]:
raw = np.array(range(1,17))
raw = raw.reshape(4,4)
raw

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
raw[0:2, 1 : 3]

array([[2, 3],
       [6, 7]])

In [55]:
raw[1:,2:]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [56]:
features = raw[:,:-1]
features

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [57]:
label = raw[:,-1]
label

array([ 4,  8, 12, 16])

In [58]:
data = list(zip(features,label))
data

[(array([1, 2, 3]), 4),
 (array([5, 6, 7]), 8),
 (array([ 9, 10, 11]), 12),
 (array([13, 14, 15]), 16)]

In [59]:
test = [data[0]]
test

[(array([1, 2, 3]), 4)]

In [40]:
train = data[1:]
train

[(array([5, 6, 7]), 8), (array([ 9, 10, 11]), 12), (array([13, 14, 15]), 16)]

In [ ]:
# Si entiendo bien la pregunta lo que pide es si separo a la poblacion que le gusta smash como nuevo universo.
# cual es la probabilidad de que le guste zelda en esta nueva poblacion (a alguien que le gusta smash)?
# la probabilidad seria 50%

In [ ]:
# si la prueba fuera 100% efectiva tendria una probabilidad del .1% de estar enfermo.
# la prueba tiene una eficacia del 99% por lo que mi probabilidad de estar enfermo es .099%

In [41]:
#f(x) = (x^3)*cos(x^2)
#f'(x) = 3*(x^2)*cos(x^2) - 2*(x^4)*sen(x^2)

In [42]:
#f(x) = (x^2)*sin(x) + x^4
#f'(x) = 2*x*sin(x) + (x^2)*cos(x) + 4*x^3

In [43]:
#f(x,z) = x^3 + z*x^2 + x*z^2 + z^3
#df/dx = 3*x^2 + 2*x*z + z^2
#df/dz = 3*z^2 + 2*x*z + x^2